// The Conservative key against its Golden corpus.
//
// Every assertion here goes through the published entry point and the exported
// corpus. Nothing reaches into a table, a helper or a private module: those are
// the parts most likely to be rewritten, and nothing outside the package should
// depend on their shape.

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";

import { conservativeKey } from "../index.js";
import { corpus } from "../fixtures/corpus.js";

test("the corpus is large enough to be worth the name", () => {
  assert.ok(corpus.length >= 25, `the corpus carries ${corpus.length} cases, expected at least 25`);
});

for (const [index, kase] of corpus.entries()) {
  test(`corpus[${index}]: ${kase.note}`, () => {
    assert.equal(conservativeKey(kase.input), kase.conservative);
  });
}

test("the key is a fixed point: keying a key returns it unchanged", () => {
  for (const kase of corpus) {
    const key = conservativeKey(kase.input);
    assert.equal(conservativeKey(key), key, `not idempotent for ${JSON.stringify(kase.input)}`);
  }
});

test("the key is stable across repeated calls in one process", () => {
  for (const kase of corpus) {
    assert.equal(conservativeKey(kase.input), conservativeKey(kase.input));
  }
});

// A second process, not a second import: a cache-busting query still hands back
// the same function object from the module graph underneath, so it would prove
// nothing about a key generated by a build that is not this one.
test("the key is the same in a process that imports the package fresh", () => {
  const index = new URL("../index.js", import.meta.url).href;
  const fixture = new URL("../fixtures/corpus.js", import.meta.url).href;
  const program = `
    const [{ conservativeKey }, { corpus }] = await Promise.all([
      import(${JSON.stringify(index)}),
      import(${JSON.stringify(fixture)}),
    ]);
    process.stdout.write(JSON.stringify(corpus.map((c) => conservativeKey(c.input))));
  `;
  const keys = JSON.parse(execFileSync(process.execPath, ["--input-type=module", "-e", program], { encoding: "utf-8" }));
  assert.deepEqual(keys, corpus.map((kase) => kase.conservative));
});

// Spelling independence. The same name, written the ways a Source or a keyboard
// actually writes it, must key byte for byte the same. This is the property that
// lets the package own its tables instead of asking the host to decompose text.
const SPELLINGS = [
  {
    name: "Bejaia",
    key: "bejaia",
    spellings: ["Béjaïa", "Béjäia"],
  },
  {
    name: "Ain Temouchent",
    key: "ain temouchent",
    spellings: ["Aïn Témouchent", "Aïn Témouchent"],
  },
  {
    name: "Adrar",
    key: "ادرار",
    spellings: ["أدرار", "أدرار", "ﺃﺩﺭﺍﺭ", "ٱدرار", "ﭐدرار"],
  },
  {
    name: "Alger",
    key: "الجزاير",
    spellings: ["الجزائر", "الجـــزائر", "ﺍﻟﺠﺰﺍﺋﺮ"],
  },
];

for (const { name, key, spellings } of SPELLINGS) {
  test(`${name}: every spelling keys to ${JSON.stringify(key)}`, () => {
    for (const spelling of spellings) {
      assert.equal(conservativeKey(spelling), key, `spelling ${JSON.stringify(spelling)}`);
    }
  });
}
